# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fFdWw8WcKMZYLnW_U9RjD2H3yh8sZIhH
"""

import requests
from geopy.geocoders import Nominatim
import folium

places = [
  {"name": "Penn Station"},
  {"name": "Empire State Building"},
  {"name": "Times Square"},
  {"name": "One World Trade Center"},
  {"name": "Battery Park"},
  ]

geolocator = Nominatim(user_agent="my_nyc_app")
my_map=folium.Map(location=[40.749256, -73.990883], zoom_start=12)

route_path = []

for place in places:
  loc = geolocator.geocode(place["name"])

  if loc:
    route_path.append([loc.latitude, loc.longitude])
    folium.Marker(
        [loc.latitude, loc.longitude]
        , popup=place["name"]
      ).add_to(my_map)
  else:
    print(f"Could not geocode: {place["name"]}")

coord_str = ";".join([f"{pt[1]},{pt[0]}" for pt in route_path])

osrm_url = f"http://router.project-osrm.org/route/v1/driving/{coord_str}?overview=full&geometries=geojson"

response = requests.get(osrm_url)
route_data = response.json()

if "routes" in route_data and len(route_data["routes"]) > 0:
    street_coords = [
        [coord[1], coord[0]]
        for coord in route_data["routes"][0]["geometry"]["coordinates"]
    ]

folium.PolyLine(
    locations=street_coords,
    color="blue",
    weight=5,
    opacity=0.8,
    tooltip="NYC Tour Route"
).add_to(my_map)

my_map

